### PR TITLE
Updating ARM diagram to draw.io

### PR DESCRIPTION
**Pull request by danclegg**

### CODE REVIEW

**Comment by danclegg** [comment]
This is just a doc update

**Comment by danclegg** [comment]
Updated color scheme to match https://brand.byu.edu/guidelines/color/

**Comment by dannyrandall** [comment]
@danclegg We can't merge this until you either build it in circle or make a branch on our account ¯\_(ツ)_/¯

**Comment by danclegg** [comment]
I will resubmit from a local branch as this was done from a fork.

**Pull request closed without merging**
